/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients/$clientId'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices/$invoiceId'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices/new'
import { Route as AppReceiptsIndexRouteImport } from './routes/_app/receipts/index'
import { Route as AppReceiptsReceiptIdRouteImport } from './routes/_app/receipts/$receiptId'
import { Route as AppTeamIndexRouteImport } from './routes/_app/team/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppInvoicesInvoiceIdIndexRouteImport } from './routes/_app/invoices/$invoiceId/index'
import { Route as AppInvoicesInvoiceIdEditRouteImport } from './routes/_app/invoices/$invoiceId/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsIndexRoute = AppReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsReceiptIdRoute = AppReceiptsReceiptIdRouteImport.update({
  id: '/receipts/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInvoicesInvoiceIdIndexRoute =
  AppInvoicesInvoiceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppInvoicesInvoiceIdRoute,
  } as any)
const AppInvoicesInvoiceIdEditRoute =
  AppInvoicesInvoiceIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppInvoicesInvoiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/payments': typeof AppPaymentsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRouteWithChildren
  '/invoices/new': typeof AppInvoicesNewRoute
  '/receipts/$receiptId': typeof AppReceiptsReceiptIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/clients/': typeof AppClientsIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/receipts/': typeof AppReceiptsIndexRoute
  '/team/': typeof AppTeamIndexRoute
  '/invoices/$invoiceId/edit': typeof AppInvoicesInvoiceIdEditRoute
  '/invoices/$invoiceId/': typeof AppInvoicesInvoiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/payments': typeof AppPaymentsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/': typeof AppIndexRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/receipts/$receiptId': typeof AppReceiptsReceiptIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/clients': typeof AppClientsIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/receipts': typeof AppReceiptsIndexRoute
  '/team': typeof AppTeamIndexRoute
  '/invoices/$invoiceId/edit': typeof AppInvoicesInvoiceIdEditRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRouteWithChildren
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/receipts/$receiptId': typeof AppReceiptsReceiptIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/receipts/': typeof AppReceiptsIndexRoute
  '/_app/team/': typeof AppTeamIndexRoute
  '/_app/invoices/$invoiceId/edit': typeof AppInvoicesInvoiceIdEditRoute
  '/_app/invoices/$invoiceId/': typeof AppInvoicesInvoiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/login'
    | '/analytics'
    | '/payments'
    | '/services'
    | '/settings'
    | '/transactions'
    | '/clients/$clientId'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/receipts/$receiptId'
    | '/api/auth/$'
    | '/clients/'
    | '/invoices/'
    | '/receipts/'
    | '/team/'
    | '/invoices/$invoiceId/edit'
    | '/invoices/$invoiceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invite'
    | '/login'
    | '/analytics'
    | '/payments'
    | '/services'
    | '/settings'
    | '/transactions'
    | '/'
    | '/clients/$clientId'
    | '/invoices/new'
    | '/receipts/$receiptId'
    | '/api/auth/$'
    | '/clients'
    | '/invoices'
    | '/receipts'
    | '/team'
    | '/invoices/$invoiceId/edit'
    | '/invoices/$invoiceId'
  id:
    | '__root__'
    | '/_app'
    | '/invite'
    | '/login'
    | '/_app/analytics'
    | '/_app/payments'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/transactions'
    | '/_app/'
    | '/_app/clients/$clientId'
    | '/_app/invoices/$invoiceId'
    | '/_app/invoices/new'
    | '/_app/receipts/$receiptId'
    | '/api/auth/$'
    | '/_app/clients/'
    | '/_app/invoices/'
    | '/_app/receipts/'
    | '/_app/team/'
    | '/_app/invoices/$invoiceId/edit'
    | '/_app/invoices/$invoiceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipts/': {
      id: '/_app/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof AppReceiptsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipts/$receiptId': {
      id: '/_app/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof AppReceiptsReceiptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/': {
      id: '/_app/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/invoices/$invoiceId/': {
      id: '/_app/invoices/$invoiceId/'
      path: '/'
      fullPath: '/invoices/$invoiceId/'
      preLoaderRoute: typeof AppInvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof AppInvoicesInvoiceIdRoute
    }
    '/_app/invoices/$invoiceId/edit': {
      id: '/_app/invoices/$invoiceId/edit'
      path: '/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof AppInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof AppInvoicesInvoiceIdRoute
    }
  }
}

interface AppInvoicesInvoiceIdRouteChildren {
  AppInvoicesInvoiceIdEditRoute: typeof AppInvoicesInvoiceIdEditRoute
  AppInvoicesInvoiceIdIndexRoute: typeof AppInvoicesInvoiceIdIndexRoute
}

const AppInvoicesInvoiceIdRouteChildren: AppInvoicesInvoiceIdRouteChildren = {
  AppInvoicesInvoiceIdEditRoute: AppInvoicesInvoiceIdEditRoute,
  AppInvoicesInvoiceIdIndexRoute: AppInvoicesInvoiceIdIndexRoute,
}

const AppInvoicesInvoiceIdRouteWithChildren =
  AppInvoicesInvoiceIdRoute._addFileChildren(AppInvoicesInvoiceIdRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRouteWithChildren
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppReceiptsReceiptIdRoute: typeof AppReceiptsReceiptIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppReceiptsIndexRoute: typeof AppReceiptsIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRouteWithChildren,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppReceiptsReceiptIdRoute: AppReceiptsReceiptIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppReceiptsIndexRoute: AppReceiptsIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
